# Site settings
title: News-breaking. Code-wrangling
header-img: img/home-bg.png
email: beckybratu@gmail.com
copyright_name: beckybratu
description: > # this means to ignore newlines until "baseurl:"
  Journalist learning to code. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: beckybratu
github_username:  beckybratu
learn_profile: beckybratu
email_username: beckybratu@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
